### PR TITLE
some new placeholders and fix

### LINKED ISSUE #14: Direction
%player_direction%
This provides the wrong direction.
I am facing North but the placeholder says East

### PR DESCRIPTION
**Pull request by aBo0oDyy**
Added:
%player_colored_ping% with changeable colors from papi config (Requested by Adam)
%player_biome% (Requested by Adam)
%player_item_in_offhand_level_<ench>%  cuz why not

Fixes #14 
and hopefully made the code a little bit cleaner
https://aboodyy.net/PAPI-Expansion-Player.jar

### CODE REVIEW

**Comment by aBo0oDyy** [comment]
hmmm? [https://img.aboodyy.net/19.04.26_01-52.png](https://img.aboodyy.net/19.04.26_01-52.png)
i didnt change all of that ;p

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java [hunk 1]
```diff
@@ -1,270 +1,293 @@
...
+        return defaults;
+    }
+
+    public String onRequest(OfflinePlayer player, String identifier) {
+        high = this.getString("ping_color.high", "&a");
+        medium = this.getString("ping_color.medium", "&e");
+        low = this.getString("ping_color.low", "&c");
+
+        if (identifier.startsWith("ping_")) {
+            identifier = identifier.split("ping_")[1];
```
Comment (Andre601) [inline src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: This could throw an error, if you only use `%player_ping_%`
Should probably have a check fro if the string is empty.

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java [hunk 2]
```diff
@@ -1,270 +1,293 @@
...
+            Player t = Bukkit.getPlayer(identifier);
+            if (t != null) {
+                return getPing(t);
+            }
+            return "0";
+        }
+        if (identifier.startsWith("colored_ping_")) {
+            identifier = identifier.split("colored_ping_")[1];
```
Comment (Andre601) [inline src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: Same reason like in other message.
Also why target a different player here?

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java [hunk 3]
```diff
@@ -1,270 +1,293 @@
...
+                return player.getBedSpawnLocation() != null ? player.getBedSpawnLocation().getWorld()
+                        .getName() : "";
+        }
+
+        // online placeholders
+        if (!player.isOnline()) {
+            return "";
+        }
+
+        Player p = player.getPlayer();
```
Comment (Andre601) [inline src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: Is that one actually required for a OfflinePlayer?
Does it not just act as a normal player when they are online?

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java [hunk 4]
```diff
@@ -1,270 +1,293 @@
...
+
+        if (identifier.startsWith("has_permission_")) {
+            String perm = identifier.split("has_permission_")[1];
```
Comment (Andre601) [inline src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: Could throw error

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java [hunk 5]
```diff
@@ -1,270 +1,293 @@
...
+            return bool(p.hasPermission(perm));
+        }
+
+        if (identifier.startsWith("item_in_hand_level_")){
+            String enchantment = identifier.split("item_in_hand_level_")[1];
```
Comment (Andre601) [inline src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: Could throw error

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java [hunk 6]
```diff
@@ -1,270 +1,293 @@
...
+            return String.valueOf(itemInHand(p).getEnchantmentLevel(Enchantment.getByName(enchantment)));
+        }
+        if (identifier.startsWith("item_in_offhand_level_")){
+            String enchantment = identifier.split("item_in_offhand_level_")[1];
```
Comment (Andre601) [inline src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: Could throw error

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java (hunk 1 above)
Comment (aBo0oDyy) [reply src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: ok ill add that

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java (hunk 2 above)
Comment (aBo0oDyy) [reply src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: ok, and cuz its a different placeholder?

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java (hunk 3 above)
Comment (aBo0oDyy) [reply src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: OfflinePlayer isnt Player
if u want to use OffilePlayer as online ull have to add `.getPlayer` after OfflinePlayer
so that makes it easier instead of adding `.getPlayer` every time

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java (hunk 4 above)
Comment (aBo0oDyy) [reply src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: didnt mess with that but okay will fix it

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java (hunk 5 above)
Comment (aBo0oDyy) [reply src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: will fix that

File: src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java (hunk 6 above)
Comment (aBo0oDyy) [reply src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java]: will fix that

**Comment by aBo0oDyy** [comment]
Thanks for your review, all should be good now

**Comment by Andre601** [comment]
Seems good to me.
Any additional stuff @extendedclip @Funny-cube ?

**Comment by Funny-cube** [comment]
Happy to merge, assuming testing has been carried out to ensure new/old placeholders work?

**Comment by Andre601** [comment]
I myself couldn't test it since I don't have time to compile and check it.

**Comment by aBo0oDyy** [comment]
ofc i have tested it, 
[d95eaaf](https://github.com/PlaceholderAPI/Player-Expansion/pull/15/commits/d95eaaf93a5e384d79c62cb38299edebd5b7fc47) tested in 1.12.2 and 1.8.8 (i dont remember if i did in 1.13.2)
[93c6f1c](https://github.com/PlaceholderAPI/Player-Expansion/pull/15/commits/93c6f1c4fbf9c28878112625927e644fc91cde74), [9832152](https://github.com/PlaceholderAPI/Player-Expansion/pull/15/commits/98321520e21489b2c39f96821ecb4131117e4099), [cd0a9bc](https://github.com/PlaceholderAPI/Player-Expansion/pull/15/commits/cd0a9bccc18897416ecb0e1edb0f0956b9277e92), [5f04173](https://github.com/PlaceholderAPI/Player-Expansion/pull/15/commits/5f041730cf859faed3e01c2b14af642d58fb6452), [a998778](https://github.com/PlaceholderAPI/Player-Expansion/pull/15/commits/a99877877fe38d71e5ea14cb32c467bf6a5a52ae) tested in 1.12.2 only (i think it should work fine in 1.8.8-1.13.2 cuz nothing changed for that in SpigotAPI)
I tested all that placeholders that i have changed them in the code, didnt test other older placeholders since i didnt change anything for them. Tell me if u want me to test them.

i sent a link to download a complied jar for it if anyone want to double check in my first message.
@Funny-cube i didnt changed the version, do u want me to (if so it will be v1.6.5?) if u want to push an update to the cloud? or ull do that?

**Comment by Funny-cube** [comment]
Ah yeah, you'll need to change the version.

**Comment by aBo0oDyy** [comment]
Thank you clip 😁 
ill open another PR for the version @Funny-cube
